name: "Cloud Proxy Client (TM)"
version: "2.1.0"
slug: "cloud-proxy-client"
description: "Удаленный доступ для HA (На территории Туркменистана). ВАЖНО: Добавьте в configuration.yaml: http: { use_x_forwarded_for: true, trusted_proxies: [172.0.0.0/8] }"
arch:
  - aarch64
  - amd64
startup: "services"
boot: "auto"
init: false
options:
  token: ""
schema:
  token: "str"
